# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

sonar.projectKey=gridsuite_gridapp-template
sonar.organization=gridsuite
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.cpd.exclusions=**/translations/**
sonar.sources=src
sonar.exclusions=**/*.test.ts,**/*.spec.ts,**/translations/**
sonar.coverage.exclusions=\
src/types/**,\
src/**/*.d.ts,\
src/**/*.type.ts,\
src/__mocks__/**,\
src/app/providers/**,\
src/plugins/**,\
src/index.tsx